spring:
  application:
    name: userservice
  cloud:
    config:
      uri: http://localhost:8888
      import: config-server
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/userservice
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
 
management:
  endpoints:
    web:
      exposure:
        include: "*"
 
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


server:

  port: 8080 
